development:
  adapter: postgresql
  encoding: unicode
  database: ec2_development
  pool: 5
  port: 5433
  username: postgres
  password: postgres
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: ec2_test
  pool: 5
  port: 5433
  username: postgres
  password: postgres
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: ec2_production
  pool: 5
  username: postgres
  password: postgres
  host: localhost




